---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: hanjunlee/jira-537:server
          imagePullPolicy: Always
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 9000
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: grpc
