name: deploy

on:
  deployment

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Deploy success
        uses: deliverybot/deployment-status@v1
        with:
          state: success
          token: ${{ github.token }}
